### ISSUE TITLE
Optional `now` module in 0.5.x

### ISSUE THREAD

**Issue by lopopolo** [Kijewski/tzdb#133]
Hi @Kijewski, as a consumer of `tzdb`, I prefer to delegate to `tz-rs` for "now" functionality. It looks like the 0.5.x branch which is in pre-release includes a new `tzdb::now` module which depends on `utcnow`.

Would you be open to gating `tzdb::now` and the `utcnow` dependency behind an on-by-default cargo feature?

My motivation here is that I prefer to not have dependencies in my `Cargo.lock` file that my applications don't use.

I'm happy to push a PR for this if you'd like me to.

**Comment by Kijewski** [comment]
I removed the no_std support in 0.5.0-pre.3, so "utcnow" is not needed anymore. The module "now" is included without guards, now, but it does not pull in any external dependencies.

**Comment by Kijewski** [comment]
Do you think v0.5 is ready to be published? I guess it's ready and I already use it in production. I would bump the msrv to 1.56 for the release just in case, so I can use `edition = "2021"` if I need it in the future.

**Comment by lopopolo** [comment]
I'll try to find some time to kick the tires on the RC by the end of the week.
