### ISSUE TITLE
Make `iana-time-zone` dep and `local_tz` function optional

### ISSUE THREAD

**Issue by lopopolo** [Kijewski/tzdb#178]
If https://github.com/strawlab/iana-time-zone/pull/104 is merged, I'd like to depend on `iana-time-zone` directly so I can control which features are activated. I believe I'd be able to implement `local_tz` myself by calling:

```rust
let tz = tzdb::raw_tz_by_name(iana_time_zone::get_timezone()?);
```

Additionally, un-nesting `iana-time-zone` from this crate's dependency tree should improve compile times for apps depending on `tzdb` by allowing this crate (which takes 6 seconds to compile on my machine) to move earlier in the crate DAG.

**Comment by Kijewski** [comment]
I think the biggest "offender" is my macro

```rust
macro_rules! unwrap {
    ($($tt:tt)*) => {
        match $($tt)* {
            Ok(value) => value,
            Err(_) => {
                #[allow(unconditional_panic)]
                let err = [][0];
                err
            }
        }
    }
}
```

If I replace it with ↓, then the compile time is about 4 times faster in the simple test I did.

```rust
pub(crate) const fn time_zone_ref_new(
    transitions: &'static [tz::timezone::Transition],
    local_time_types: &'static [tz::LocalTimeType],
    leap_seconds: &'static [tz::timezone::LeapSecond],
    extra_rule: &'static Option<tz::timezone::TransitionRule>,
) -> TimeZoneRef<'static> {
    match TimeZoneRef::new(transitions, local_time_types, leap_seconds, extra_rule) {
        Ok(value) => value,
        Err(_) => {
            #[allow(unconditional_panic)]
            let err = [][0];
            err
        },
    }
}
```

I'll test it properly in the next few days.

Changing the default features would be a breaking change. But I could use breaking change this to increase the msrv from 1.56 to 1.57, so I could use `panic!()` in `time_zone_ref_new()`. I'll think about it. :)

**Comment by Kijewski** [comment]
Please have a look if the path I took in [`tzdb = "0.6.0-pre.1"`](https://crates.io/crates/tzdb/0.6.0-pre.1) would work for you:

* `features = ["local"]` enables function that use `iana_time_zone`.
* If included, `iana_time_zone` is always used with `feature = ["fallback"]`

**Comment by lopopolo** [comment]
This works great! thanks @Kijewski 🙇 

I've gone ahead and upgraded to tzdb v0.6.0-pre.1.

**Comment by Kijewski** [comment]
Thank you for testing the pre-release! :) I just pushed the stable release 0.6.0.
