### ISSUE TITLE
Get Current Time Zone Name

### ISSUE THREAD

**Issue by wyatt-herkamp** [Kijewski/tzdb#187]
So I would like to be able to get current time zone name? Is it possible to add that feature?

**Comment by Kijewski** [comment]
Have a look at [`iana_time_zone::get_timezone()`](https://docs.rs/iana-time-zone/0.1.58/iana_time_zone/fn.get_timezone.html).

**Comment by wyatt-herkamp** [comment]
> Have a look at [`iana_time_zone::get_timezone()`](https://docs.rs/iana-time-zone/0.1.58/iana_time_zone/fn.get_timezone.html).

Sorry it took me so long to respond. I never got notified of your response. That works thank you!
